### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by dshafik** [wpalmer/gozone#1]
Hi,

I would like to use this library in a project (and have fixes to submit upstream for support of many more kinds of records) but I cannot do that until and unless a license is added.

I would highly recommend the Apache-2.0 license or MIT license. If you are unfamiliar with Licensing, I highly recommend GitHub's [Choose a License](https://choosealicense.com) website for helping you pick which one to use.

**Comment by wpalmer** [comment]
Sorry about that. The MIT license has now been added
